In [1]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [2]:
xreshaped = x.reshape(1, 9)
xreshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [3]:
z = x.view(1, 9)
z, z.shape
# z is  aview of x hopwever, changes to z affects x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [4]:
#stack tensors on each othwer.
stackedx = torch.stack([x, x,x ,x], dim=0)
stackedx

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [5]:
xsqueezed = xreshaped.squeeze() #removes single (1) dimesnion form a tensor
xsqueezed #one square bracket removed


tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [6]:
# ttry iunsqueeze- adds a single dimension to a tensor
xunsqueezed = xsqueezed.unsqueeze(dim=0)
xunsqueezed

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [7]:
#torch.permute rearranges dimension of tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))
x_original
permuted_x = x_original.permute(2, 0, 1) # move third dimesnion (2: rememebr zero indexed) to first, first to second, and second to third
x_original[1, 1, 1], permuted_x[1, 1, 1]
# changing the permuted also changes the original 


(tensor(0.3809), tensor(0.3809))

In [8]:
#indexing data
x = torch.arange(1, 10).reshape(1, 3, 3)
x


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [9]:
x[0] #first dimension 

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [10]:
x[0][0] #second dimension
x[0, 0] # same function as above

tensor([1, 2, 3])

In [11]:
x[0][0][0] #third dimension


tensor(1)

In [12]:
# can use ":" to get all of a target dimension 
x[:, 0]

tensor([[1, 2, 3]])

In [13]:
#get all of 0th and 1st, but only inedex 1 of second dimension
x[:, :, 2]

tensor([[3, 6, 9]])

In [14]:
x[0, 0, :]

tensor([1, 2, 3])

In [15]:
#convert numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [16]:
#tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [17]:
import torch
# randomnesss
randomTensorA = torch.rand(3, 4)
randomTensorB = torch.rand(3, 4)

print(randomTensorA)
print(randomTensorB)
print(randomTensorB == randomTensorA)

tensor([[0.7264, 0.7804, 0.8396, 0.9749],
        [0.1058, 0.5529, 0.6812, 0.9716],
        [0.4768, 0.5654, 0.7269, 0.7618]])
tensor([[0.4455, 0.7072, 0.0222, 0.0676],
        [0.8461, 0.0169, 0.8743, 0.0598],
        [0.8085, 0.0696, 0.9729, 0.5141]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [18]:
#rnadom but reproducable
import torch

#set ranodm seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

randomTensorC = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
randomTensorD = torch.rand(3, 4)

print(randomTensorC)
print(randomTensorD)
print(randomTensorC == randomTensorD)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [19]:
import torch
print(torch.cuda.is_available())  # Should return True if GPU is accessible
# print(torch.cuda.device_count())  # Number of GPUs available
# print(torch.cuda.get_device_name(0))  # Name of GPU


False
